version: '3'

services:
  redis:
      image: redis:alpine3.16
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
      env_file:
        - .env
      volumes: 
        - cache:/data
      networks:
      - nginx_network

  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:8080"
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

  app:
    container_name: app
    image: note-api #Specify the name of the Docker image to be built
    build:
      context: ./note-api
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  cache:
    driver: local